name: test-deployment

on:
 push:
   branches:
     - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps: 
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Debug Secrets
        run: |
          echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" | sed 's/./& /g'
          echo "DOCKER_KEY=${{ secrets.DOCKER_TOKEN_KEY}}" | sed 's/./& /g'

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
          
      - name: Build with Gradle
        run: |
          ./gradlew clean build
          ls -al build/libs

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_TOKEN_KEY }}

      - name: Build and Push Docker image
        run: |
          sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN_KEY }}
          sudo docker build --platform linux/amd64 -t ${{ secrets.DOCKER_USERNAME }}/ci_cd .
          sudo docker tag ${{ secrets.DOCKER_USERNAME }}/ci_cd ${{ secrets.DOCKER_USERNAME }}/ci_cd:v1
          sudo docker push ${{ secrets.DOCKER_USERNAME }}/ci_cd:v1

  deploy:
      runs-on: ubuntu-22.04
      needs: build

      steps:
        - name: SSH to EC2 and deploy
          run: |
            echo ${{ secrets.EC2_KEY }} > private_key.pem
            chmod 600 private_key.pem
            ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ secrets.EC2_IP }} << EOF
              cd /home/ubuntu/test
              sudo docker compose down -v
              sudo docker pull junuary2/ci_cd:v1
              sudo docker compose up -d --build
            EOF
      
